### ISSUE TITLE
IMDB Popularity is Not Available in the API

### ISSUE THREAD

**Issue by jaruba** [linaspurinis/mdblist.com#12]
There is no way to retrieve IMDB popularity through the MDBList API atm.

We have a use for this and would like to have access to such data as well if possible.

**Comment by linaspurinis** [comment]
I added the new key to API:

```json
"ratings":[
{
"source":"imdb",
"value":7.8,
"score":78,
"votes":183981,
"popular":23,
},
```
IMDB Popularity rating numbers displayed on mdblist.com is not an exact representation of IMDB Popularity, because they are refreshed alongside movies over time and are representations of movie rating available at the time of the metadata refresh of this specific movie. Only the top 100 popularity data is pulled every day from IMDb.

**Comment by jaruba** [comment]
@linaspurinis we tested and it seems to work as expected, thanks!
